### ISSUE TITLE
MTBF full run issue - first iterative

### ISSUE THREAD

**Issue by ypwalter** [Mozilla-TWQA/gaia#19]
http://mtbf-1.corp.tpe1.mozilla.com:8080/view/v1.3/job/hamachi.v130.mtbf/9/consoleFull

TEST-UNEXPECTED-FAIL | test_calendar_new_event_appears_on_all_calendar_views.py test_calendar_new_event_appears_on_all_calendar_views.TestCalendar.test_that_new_event_appears_on_all_calendar_views | NoSuchElementException: Unable to locate element: #event-list section.hour-3 div.events

TEST-UNEXPECTED-FAIL | test_calendar_new_event_appears_on_all_calendar_views.py test_calendar_new_event_appears_on_all_calendar_views.TestCalendar.test_that_new_event_appears_on_all_calendar_views | NoSuchElementException: Unable to locate element: //a[@href='/month/']

TEST-UNEXPECTED-FAIL | test_mtbf_dialer_airplane_mode.py test_mtbf_dialer_airplane_mode.TestDialerAirplaneMode.test_dialer_airplane_mode | TimeoutException: Element confirmation-message present but not displayed before timeout

TEST-UNEXPECTED-FAIL | test_mtbf_dialer.py test_mtbf_dialer.TestDialer.test_dialer_make_call | TimeoutException: Element iframe[name*='call_screen'] not found before timeout

TEST-UNEXPECTED-FAIL | test_mtbf_MMI.py test_mtbf_MMI.TestMMI.test_MMI_code_IMEI | 

TEST-UNEXPECTED-FAIL | test_mtbf_call_log_all_calls.py test_mtbf_call_log_all_calls.TestCallLogAllCalls.test_call_log_all_calls | TimeoutException: Element iframe[name*='call_screen'] not found before timeout

TEST-UNEXPECTED-FAIL | test_mtbf_settings_device_info.py test_mtbf_settings_device_info.TestSettingsDeviceInfo.test_that_device_info_is_populated | 

TEST-UNEXPECTED-FAIL | test_play_mp4_video.py test_play_mp4_video.TestPlayMP4Video.test_play_mp4_video | ScriptTimeoutException: timed out

TEST-UNEXPECTED-FAIL | test_play_3gp_video.py test_play_3gp_video.TestPlay3GPVideo.test_play_3gp_video | ScriptTimeoutException: timed out

TEST-UNEXPECTED-FAIL | test_video_empty.py test_video_empty.TestVideoEmpty.test_empty_video | ElementNotVisibleException: Element is not currently visible and may not be manipulated

10:40:25 test_calendar_new_event_appears_on_all_calendar_views.py test_calendar_new_event_appears_on_all_calendar_views.TestCalendar.test_that_new_event_appears_on_all_calendar_views
10:40:25 test_calendar_new_event_appears_on_all_calendar_views.py test_calendar_new_event_appears_on_all_calendar_views.TestCalendar.test_that_new_event_appears_on_all_calendar_views
10:40:25 test_mtbf_dialer_airplane_mode.py test_mtbf_dialer_airplane_mode.TestDialerAirplaneMode.test_dialer_airplane_mode
10:40:25 test_mtbf_dialer.py test_mtbf_dialer.TestDialer.test_dialer_make_call
10:40:25 test_mtbf_MMI.py test_mtbf_MMI.TestMMI.test_MMI_code_IMEI
10:40:25 test_mtbf_call_log_all_calls.py test_mtbf_call_log_all_calls.TestCallLogAllCalls.test_call_log_all_calls
10:40:25 test_mtbf_settings_device_info.py test_mtbf_settings_device_info.TestSettingsDeviceInfo.test_that_device_info_is_populated
10:40:25 test_play_mp4_video.py test_play_mp4_video.TestPlayMP4Video.test_play_mp4_video
10:40:25 test_play_3gp_video.py test_play_3gp_video.TestPlay3GPVideo.test_play_3gp_video
10:40:25 test_video_empty.py test_video_empty.TestVideoEmpty.test_empty_video

**Comment by ypwalter** [comment]
needs to make the test more stable

**Comment by cjlin69** [comment]
The blocking issue of calendar case is fixed on #20.
